# Generated by Django 3.1.1 on 2020-09-30 16:49

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'especialidade   ',
            },
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=150)),
                ('CRM', models.IntegerField()),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('telefone', models.CharField(max_length=150)),
                ('especialidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medcarapi.especialidade')),
            ],
            options={
                'db_table': 'medico',
            },
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('usuario_id', models.IntegerField()),
                ('data_agendamento', models.DateTimeField(auto_now_add=True)),
                ('dia', models.DateField()),
                ('horario', models.TimeField()),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medcarapi.medico')),
            ],
            options={
                'db_table': 'consulta',
            },
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('dia', models.DateField()),
                ('horarios', django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(), size=None)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medcarapi.medico')),
            ],
            options={
                'db_table': 'agenda',
            },
        ),
    ]
